version: "3.9"

services:
  app:
    container_name: supersettings
    image: javimosch/supersettings:latest
    working_dir: /app
    expose:
      - "3006"
    env_file:
      - ./.env
    command: ["node", "src/server.js"]
    restart: always
